#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

runApplication blockMesh
runApplication topoSet
runApplication surfaceFeatureExtract
runApplication snappyHexMesh -overwrite

runApplication splitMeshRegions -cellZones -overwrite
runApplication -s atrium changeDictionary -region atrium
runApplication -s domain1 changeDictionary -region domain1
# Remove fluid fields from solid regions (important for post-processing)
for region in $(foamListRegions solid)
do
    rm -f 0/$region/{rho,mut,alphat,epsilon,k,U,p_rgh,qr,G,IDefault}
    rm -f processor*/0/$region/{rho,mut,alphat,epsilon,k,U,p_rgh,qr,G,IDefault}
done

restore0Dir
runApplication $(getApplication)

#------------------------------------------------------------------------------
